### ISSUE TITLE
04장 OSI 각 계층에서 처리율 제한을 처리하는 방식

### ISSUE THREAD

**Issue by newbieJanghan** [i-hate-test/System-Design-Interview-01#3]

**Comment by aihoshistar** [comment]
도메인을 타고 들어오는 트래픽은 클라우드 플레어와 같은 서비스에서 처리가 가능하나

IP 로 직접 유입되는 트래픽은 (firewall-cmd / ufw / iptables) 을 통해 관리하기도 함

**Comment by newbieJanghan** [comment]
결론
os 커널에서 패킷을 처리해서 iptables을 동작시킨다.
