### ISSUE TITLE
04장 경쟁 조건 문제 해결을 위한 루아 스크립트와 레디스 자료구조 

### ISSUE THREAD

**Issue by ghlnh** [i-hate-test/System-Design-Interview-01#7]
루아 스크립트와 레디스 정렬 집합이 어떻게 경쟁조건 문제를 해결하는지 잘 모르겠습니다

일단 아래와 같이 생각했습니다

- 루아 스크립트: 절차지향적 선언형 언어라고 하는데 아마 순차적으로 실행시켜서 경쟁을 없앤다..?

- 레디스 정렬집합: 모든 레디스 작업을 MULTI 명령을 사용하여 원자적 작업으로 수행할 수 있다. 즉, 두 개의 프로세스가 동일한 사용자에 대해 작업을 시도할 때 최신 정보가 아닌 상태가 될 수 없으므로 경쟁 조건 문제를 방지

**Comment by aihoshistar** [comment]
1. 어플리케이션이 레디스에서 `timestamp`, `카운트` 데이터를 가져와 연산을 한 후 결과를 Redis 에 추가하는 방법보단 루아 스크립트를 작성하여 Reids 에서 실행하면 어플리케이션이 병렬로 레디스에 루아 스크립트를 실행 요청을 해도 싱글 쓰레드로 동작하는 레디스는 경쟁조건의 문제를 해결할 수 있음 

2. 레디스의 자료구조 중 `Sorted Sets` 을 사용하면 순차적으로 데이터가 쌓이기 때문에 항상 최신 정보를 처리하게 됨 

이 아닐까 싶습니다.

**Comment by newbieJanghan** [comment]
https://dev.gmarket.com/69

요기 글이 엄청 좋네요. 레디스 클러스터 환경에서의 Atomic 한 연산을 다루는 기술로 lua script 를 쓰고 있습니다.

1. 레디스 자체는 싱글 스레드이므로 `WATCH`문 (optimistic lock)을 사용하거나 트랜잭션을 시도하여 경쟁 조건을 해결할 수 있습니다.
2. 다만 레디스 클러스터의 경우 각 노드 간 key 값을 모르므로 트랜잭션, lock 을 사용할 수 없습니다.
3. 레디스는 내장 lua script engine이 있습니다. 레디스는 해당 엔진으로 실행하는 script 의 atomic 실행을 보장합니다. 클러스터 환경에서도 기능합니다.
![image](https://github.com/i-hate-test/System-Design-Interview-01/assets/102276240/92a919a1-42f9-4c0b-bf37-6f9de6231db4)

정리
1. 레디스가 싱글 스레드라는 점과 lua script 의 원자성이 보장된 트랜잭션이 기능할 수 있다.
2. 클러스터 환경이 아니라면 lua script 말고도 경쟁 상태를 해결할 수 있는 방법이 있다.
3. 그럼에도 lua script는 성능이 좋고 러닝커브가 짧으므로 사용할 만하다.

**Comment by aihoshistar** [comment]
https://redis.io/docs/latest/develop/interact/programmability/triggers-and-functions/

javascript 에서 redis 에서 사용할 수 있다는
